### PR TITLE
Implement methods with Java8's Stream API

### PR DESCRIPTION
**Pull request by alexVengrovsk**

### CODE REVIEW

**Comment by alexVengrovsk** [comment]
@0xFFFFFFFE Please, have a look at my PR. If it is Ok, I will continue to work unde adding some java8's features to the .../zynamics/reil/algorithms/mono package

**Comment by alexVengrovsk** [comment]
@cblichmann I made a PR https://github.com/google/binnavi/pull/46, but I didn't have any feedback for a while. Could you have a look at it?

**Comment by 0xFFFFFFFE** [comment]
@cblichmann is currently on vacation. When he comes back he will reply.

**Comment by alexVengrovsk** [comment]
@0xFFFFFFFE O! Sorry ;), I had no idea. This PR can be checked by any collaborator. I recently had few dialogs with two of you, that is why I asked you to do this.

**Comment by cblichmann** [comment]
Please check the formatting of your contribution, it should consistently use 2 spaces for indentation and 100 chars per line.

**Comment by alexVengrovsk** [comment]
@cblichmann Sorry. I will do it

**Comment by cblichmann** [comment]
:)

**Comment by alexVengrovsk** [comment]
@cblichmann  I have one problem. I deleted my forked repository, from which this PR was created. And now to make it work I nead to rewrite all my 9 commits. Maybe, you can marge this PR and I will make changes in src/main/java/com/google/security/zynamics/zylib/ZyTree/InorderIterator.java after that.

**Comment by cblichmann** [comment]
Alright, will do. But I'm sure there's some magic sequence of Git commands that will bring back everything from this pull request :)

**Comment by alexVengrovsk** [comment]
:+1:

**Pull request merged**
