### PR TITLE
Independent JAR build config and missing resources fixed

### PR DESCRIPTION
**Pull request by lordqwerty**
The fat jar that was being generated by running `gradle jar` was not including certain resources causing the GUI to crash. This has now been fixed. Apologies for not spotting this sooner, would be nice to get some tests running ;) 

Also started to build independent jar building for zylib, reli and binnavi.  

See commit messages for more detail.

### CODE REVIEW

**Comment by cblichmann** [comment]
Thanks! I added some comments, please take a look.

**Comment by lordqwerty** [comment]
OK so all of the above is not an issue and can be resolved fairly quickly. Gradle cannot be downloaded by Maven however the `gradlew` files are a wrapper that can use gradle without the need of installing it. All the user requires Java on their machine. 

But yes maintaining two build systems will be a pain and only one should be use. Gradle IMHO is the better choice. Clear and easy to understand if done right. A little learning will obviously need to be done, but lots of documentation available. 

If the Gradle route is not something you wish not to use then I will cease development on it. Have a think and if you want to use Gradle I will address the above issues, if not then I can do a PR to delete all the Gradle. Let me know either way :)

**Comment by 0xFFFFFFFE** [comment]
I discussed this with @cblichmann and we think you should go ahead with the Gradle integration. Please make sure to address the comments and then we will merge your changes. Thank you for putting so much work into this it is greatly appreciated.

**Comment by cblichmann** [comment]
+1
So I suggest the following: Keep Maven while you're working on the Gradle files. We should then switch over to Gradle completely. Is the project structure viable for doing this?

**Comment by lordqwerty** [comment]
I'm at work at the moment so will not get a chance to look until later
tonight.

I think a full switch is viable, but what I suggest is to:
1. I'll address the comments.
2. Merge
3. Feature branch with a full gradle and maven deleted.
4. Test test test.
5. Merge. Welcome to gradle.

That way the project stays running and up to date while we get gradle to a
point we're all happy with. :)

**Comment by cblichmann** [comment]
Awesome!

**Comment by cblichmann** [comment]
For the record, [this](http://technologyconversations.com/2014/06/18/build-tools/) is what mostly convinced me.

**Comment by bmihaila** [comment]
Yes, read that article some time ago and it really illustrates well the difference in verbosity. However, the comments to the article were mostly not that positive towards Gradle. Anyways, I'm fully in support of trying Gradle out as I accumulated too many scars already from Maven :wink: .

So if I interpret https://github.com/google/binnavi/pull/20#issuecomment-136961460 correctly the plan is to move to Gradle as the standard build system and skip Maven altogether?

Then let' s try out how Eclipse handles Gradle. :smiley:

**Comment by 0xFFFFFFFE** [comment]
Sounds like a good plan :)

**Comment by bmihaila** [comment]
Ok, played around with the current `build.gradle` and Eclipse. Here my preliminary and negative experiences. Note however that using Gradle from the command line works fine. This is only about the Eclipse integration.
1. Using the build description in the README, i.e. letting Gradle generate an Eclipse project file and then import everything as a new project into Eclipse leads to some errors concerning the classpath includes/excludes that need manual fixing as described in the Eclipse build with Ant.
   This approach also has the drawback that whenever the `build.gradle` file is changed one needs to regenerate a project file for Eclipse. Guess no need for a reimport though but have not tried. Still think it is a little bit inflexible. 
2. Adding some of the Eclipse Gradle plugins does not work yet. In theory one should  import a new Gradle project into Eclipse using "Import->Gradle->Gradle Project" and everything ought to work out of the box. This would also mean that any change to the buildfile are immediately updated into your Eclipse project.
   However, here Eclipse seems to take the `resources.include` path in the buildfile over the `java.exclude` and is then missing the main sources in the project. Removing the resources part fixes this but then we miss the resources. So there seems to be a bug that Eclipse takes the resources as source folders if given in the `sourcesSet`. Googling around did not find a solution yet. Will wait till @lordqwerty latest changes are pulled in and try again or open a bug for that.

For now back to the Ant project for Eclipse. Ooh the build system woes, they never seem to go away ...

On another note there seems to be two different (or more?) Gradle plugins for Eclipse. I tried both and they both have the bug above and do only seem to differ in the UI they have in Eclipse. Does anyone have a recommendation as to what is the Gradle plugin to use in Eclipse?

Bye
Bogdan

**Comment by cblichmann** [comment]
Hm, IntelliJ seems to be the new hotness :P
At least that's what Android Studio is based on (which also uses Gradle).

**Comment by lordqwerty** [comment]
IntelliJ is much better in my opinion. But I will still fix the above
issues.

Sorry for not sorting this sooner worked late and traveling today. Will
have the PR done by tonight.

**Comment by cblichmann** [comment]
We're not in a hurry with this. Take as much time as you need.

**Comment by bmihaila** [comment]
Yeah no hurry about Gradle, things should be done well. Take your time.

Regarding IntelliJ, yes I know it is the hotness so I might revisit it after years. But switching IDEs is always slow :). On the other hand Eclipse is really pushing one away as hard as possible by times.

**Comment by lordqwerty** [comment]
Sorry I am not going to have time to do this.

**Pull request closed without merging**
